import type { DemoSnapshot, LearningSignal, ServiceCase, Interaction } from './types'

const demo = (system: string, capturedAt: string, freshness: string) => ({
  system,
  capturedAt,
  freshness,
  demo: true as const,
})

const mayaOptions = [
  {
    id: 'opt-ei60',
    recommended: true,
    airline: 'Aer Lingus',
    flight: 'EI 60',
    route: 'DUB → JFK',
    depart: '16:15',
    arrive: '18:55',
    duration: '7h 40m',
    cabin: 'Business Flex',
    seats: 2,
    travellerCost: '€0',
    policyFit: 'Same-day disruption waiver · fare family protected',
    confidence: 91,
    risks: ['Airport wait ~3h 20m from current position (already airside).'],
    evidence: [
      {
        id: 'e1',
        label: 'Inventory',
        value: '2 J seats, last ping 07:14',
        source: demo('TravelXen inventory', '07:14', '4 min ago'),
      },
      {
        id: 'e2',
        label: 'Policy',
        value: 'Flex Business same-day reissue, no residual',
        source: demo('TravelXen policy', '07:11', '7 min ago'),
      },
      {
        id: 'e3',
        label: 'Constraint',
        value: 'Arrives before 19:30 ET client meeting',
        source: demo('Calendar + case note', '07:09', '9 min ago'),
      },
    ],
    notes: 'Ava already confirmed Maya will accept a 3h hold if she lands before 19:00 ET.',
  },
  {
    id: 'opt-aa47',
    airline: 'American Airlines',
    flight: 'AA 47',
    route: 'DUB → JFK',
    depart: '17:40',
    arrive: '20:10',
    duration: '7h 30m',
    cabin: 'Business',
    seats: 4,
    travellerCost: '€86 residual',
    policyFit: 'Within €150 disruption cap · partner carrier',
    confidence: 88,
    risks: ['Arrives after 19:30 ET meeting. Residual requires consultant acknowledgement.'],
    evidence: [
      {
        id: 'e4',
        label: 'Inventory',
        value: '4 J seats, last ping 07:14',
        source: demo('TravelXen inventory', '07:14', '4 min ago'),
      },
      {
        id: 'e5',
        label: 'Policy',
        value: 'Partner reissue allowed; residual €86 vs €150 cap',
        source: demo('TravelXen policy', '07:11', '7 min ago'),
      },
    ],
    notes: 'Use only if EI 60 inventory drops or Maya declines the wait.',
  },
  {
    id: 'opt-overnight',
    airline: 'British Airways',
    flight: 'BA 831 + BA 117',
    route: 'DUB → LHR → JFK',
    depart: '21:10 + 10:00',
    arrive: '12:35 +1',
    duration: 'Overnight + 8h 10m',
    cabin: 'Club World',
    seats: 6,
    travellerCost: '€0 + hotel',
    policyFit: 'Hotel, transfers and meals covered under disruption policy',
    confidence: 96,
    risks: ['Misses 19:30 ET meeting. Maya asked to avoid overnight if a same-day seat exists.'],
    evidence: [
      {
        id: 'e6',
        label: 'Duty of care',
        value: 'Clayton Hotel Dublin Airport, prepaid hold until 18:00',
        source: demo('TravelXen hotels', '07:12', '6 min ago'),
      },
    ],
    notes: 'Fallback if same-day inventory fails at ticketing.',
  },
]

function mayaCase(): ServiceCase {
  return {
    id: 'case-maya',
    interactionId: 'int-maya',
    caseNumber: 'TX-1842',
    traveller: 'Maya Patel',
    company: 'Meridian Analytics',
    role: 'Director, Client Delivery',
    phone: '+44 7700 900184',
    email: 'maya.patel@meridian-analytics.example',
    channel: 'whatsapp',
    intent: 'Missed connection / urgent rebooking',
    summary:
      'Inbound BA 832 LHR–DUB arrived 94 minutes late. Maya missed EI 154 DUB–JFK (11:40). She is airside at Dublin T2 and must reach JFK before a 19:30 ET client meeting. Ava identified the PNR, offered self-serve rebook, and escalated after Maya asked for a human to protect fare family and meeting time.',
    urgency: 'urgent',
    confidence: 93,
    contextCompleteness: 96,
    workflow: 'rebook',
    inventoryFresh: true,
    stage: 'brief_ready',
    selectedOptionId: null,
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'M4YAPT',
    newPnr: null,
    policy: 'Flex Business · same-day disruption waiver',
    trip: 'London → New York · 18–22 Aug 2026',
    originBooking: 'BA 832 LHR–DUB 06:40 / EI 154 DUB–JFK 11:40',
    segments: [
      {
        from: 'LHR',
        fromCity: 'London',
        to: 'DUB',
        toCity: 'Dublin',
        flight: 'BA 832',
        airline: 'British Airways',
        depart: '06:40',
        arrive: '08:12',
        status: 'delayed',
      },
      {
        from: 'DUB',
        fromCity: 'Dublin',
        to: 'JFK',
        toCity: 'New York',
        flight: 'EI 154',
        airline: 'Aer Lingus',
        depart: '11:40',
        arrive: '14:05',
        status: 'missed',
      },
    ],
    disruption: 'Missed connection at DUB after BA 832 inbound delay (94 min)',
    preferences: ['Same-day arrival', 'Aisle', 'Protect business fare family', 'No overnight if avoidable'],
    loyalty: 'AerClub Silver · BA Gold',
    locationNow: 'Dublin Airport T2 · airside · lounge access yes',
    meetingConstraint: 'Client workshop, 19:30 ET, One World Trade Center',
    avaOutcome: 'Escalated — traveller requested consultant for fare protection and meeting constraint',
    avaPlan: [
      'Keep EI 60 Business on hold (in policy, €0 residual)',
      'Reissue same fare family in TravelXen',
      'Send WhatsApp only after ticketing verifies',
    ],
    resolvedByAva: false,
    genesysQueue: 'Genesys · WhatsApp · Skill: Disruption-Rebook · demo data',
    nextBestActions: [
      {
        id: 'nba-ava-maya',
        label: 'Attest the 19:30 meeting, then hand EI 60 back to Ava',
        reason: 'Same-day, €0, fare family protected. Ava can ticket once a consultant confirms the constraint.',
        owner: 'ava',
      },
      {
        id: 'nba1',
        label: 'Protect EI 60 16:15 DUB–JFK',
        reason: 'Only same-day option that lands before the 19:30 ET meeting with €0 residual.',
        owner: 'consultant',
      },
      {
        id: 'nba2',
        label: 'Hold AA 47 as fallback for 20 minutes',
        reason: 'Inventory is deeper if EI 60 fails at ticket issue.',
        owner: 'consultant',
      },
      {
        id: 'nba3',
        label: 'Do not send a room-ready-style promise until PNR is reissued',
        reason: 'Traveller is waiting in a lounge; premature confirmation created a prior complaint on this account.',
        owner: 'consultant',
      },
    ],
    timeline: [
      { id: 't1', time: '06:40', actor: 'Carrier', label: 'BA 832 departed LHR late', detail: 'ATC slot · demo data' },
      { id: 't2', time: '09:52', actor: 'TravelXen', label: 'Disruption watch opened', detail: 'Connection risk flagged at DUB' },
      { id: 't3', time: '10:18', actor: 'Ava', label: 'Proactive WhatsApp sent', detail: 'Offered self-serve rebook; Maya replied' },
      { id: 't4', time: '11:44', actor: 'Airport', label: 'EI 154 departed without Maya', detail: 'Gate closed 11:28' },
      { id: 't5', time: '11:51', actor: 'Maya', label: 'Asked for a consultant', detail: 'Needs fare family + 19:30 ET arrival' },
      { id: 't6', time: '11:52', actor: 'Ava', label: 'Escalated to consultant queue', detail: 'Context completeness 96%' },
    ],
    transcript: [
      { time: '10:18', from: 'Ava', text: 'Maya, BA 832 is running late. Your DUB–JFK connection is at risk. I can move you if you want.' },
      { time: '10:21', from: 'Maya', text: 'Please protect business and I have a 7:30pm meeting in New York. Don’t overnight me unless there is no other seat.' },
      { time: '11:51', from: 'Maya', text: 'I missed it. Can a person handle this? I don’t want the fare stripped.' },
      { time: '11:52', from: 'Ava', text: 'I’ve escalated you with your PNR, policy, meeting time and preferred same-day options. A consultant has the case.' },
    ],
    options: mayaOptions,
    messagePreview: {
      channel: 'whatsapp',
      to: 'Maya Patel · +44 7700 900184',
      body: 'Maya — you’re confirmed on EI 60, DUB–JFK, 16:15–18:55 in Business. Boarding from T2, original fare protected, no extra cost. I’ll send the boarding pass as soon as ticketing verifies. — Alex, Navan consultant (demo)',
    },
  }
}

function danielCase(): ServiceCase {
  return {
    id: 'case-daniel',
    interactionId: 'int-daniel',
    caseNumber: 'TX-1843',
    traveller: 'Daniel Kim',
    company: 'Northwind Robotics',
    role: 'VP Engineering',
    phone: '+1 415 555 0142',
    email: 'daniel.kim@northwind-robotics.example',
    channel: 'phone',
    intent: 'Flight cancelled',
    summary:
      'UA 918 SFO–EWR cancelled for crew legality. Daniel is in the SFO United Club. Ava is still assembling alternate inventory; Genesys has parked the call in disruption triage.',
    urgency: 'high',
    confidence: 71,
    contextCompleteness: 64,
    workflow: 'triage',
    inventoryFresh: false,
    stage: 'intake',
    selectedOptionId: null,
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'DK918SF',
    newPnr: null,
    policy: 'Standard refundable · 3h connection buffer preferred',
    trip: 'San Francisco → Newark · 18 Aug 2026',
    originBooking: 'UA 918 SFO–EWR 08:15',
    segments: [
      {
        from: 'SFO',
        fromCity: 'San Francisco',
        to: 'EWR',
        toCity: 'Newark',
        flight: 'UA 918',
        airline: 'United',
        depart: '08:15',
        arrive: '16:48',
        status: 'missed',
      },
    ],
    disruption: 'UA 918 cancelled · crew legality',
    preferences: ['Same-day', 'Window', 'Avoid EWR after 22:00'],
    loyalty: 'MileagePlus Premier Gold',
    locationNow: 'SFO United Club · T3',
    meetingConstraint: 'Board dinner 20:00 ET, Midtown',
    avaOutcome: 'Waiting for triage — inventory snapshot incomplete',
    avaPlan: [
      'Refresh UA inventory until freshness < 5 min',
      'If UA 15 Polaris still available at $0, auto-ticket',
      'Hold the live call until snapshot is current',
    ],
    resolvedByAva: false,
    genesysQueue: 'Genesys · Voice · Skill: Disruption-Triage · demo data',
    nextBestActions: [
      {
        id: 'nba-d1',
        label: 'Finish inventory snapshot before promising a flight',
        reason: 'Confidence is 71% because partner availability is still refreshing.',
        owner: 'ava',
      },
    ],
    timeline: [
      { id: 'td1', time: '07:02', actor: 'United', label: 'UA 918 cancelled', detail: 'Crew legality · demo data' },
      { id: 'td2', time: '07:06', actor: 'Genesys', label: 'Inbound call queued', detail: 'IVR intent: cancellation' },
    ],
    transcript: [
      { time: '07:06', from: 'Daniel', text: 'UA 918 just cancelled. I need Newark tonight.' },
      { time: '07:07', from: 'Ava', text: 'I’m pulling alternatives. I’m keeping you with a consultant if inventory is constrained.' },
    ],
    options: [
      {
        id: 'opt-ua15',
        recommended: true,
        airline: 'United',
        flight: 'UA 15',
        route: 'SFO → EWR',
        depart: '11:05',
        arrive: '19:42',
        duration: '5h 37m',
        cabin: 'Polaris',
        seats: 1,
        travellerCost: '$0',
        policyFit: 'Same fare family · last Polaris seat',
        confidence: 74,
        risks: ['Single seat. Snapshot still refreshing.'],
        evidence: [
          {
            id: 'ed1',
            label: 'Inventory',
            value: '1 P seat, stale 11 min',
            source: demo('TravelXen inventory', '07:07', '11 min ago'),
          },
        ],
        notes: 'Do not ticket until snapshot freshness is under 5 minutes.',
      },
    ],
    messagePreview: {
      channel: 'phone',
      to: 'Daniel Kim · +1 415 555 0142',
      body: 'Daniel — holding UA 15 Polaris SFO–EWR 11:05, arriving 19:42. I’ll confirm once inventory freshness is current. (demo)',
    },
  }
}

function oliviaCase(): ServiceCase {
  return {
    id: 'case-olivia',
    interactionId: 'int-olivia',
    caseNumber: 'TX-1844',
    traveller: 'Olivia Stone',
    company: 'Brightline Media',
    role: 'Producer',
    phone: '+44 7700 900221',
    email: 'olivia.stone@brightline.example',
    channel: 'chat',
    intent: 'Seat selection',
    summary: 'Olivia wants an aisle seat on BA 112 JFK–LHR tomorrow. Ava is completing self-serve seat map; no consultant required unless payment fails.',
    urgency: 'low',
    confidence: 89,
    contextCompleteness: 92,
    workflow: 'ava_contained',
    inventoryFresh: true,
    stage: 'intake',
    selectedOptionId: null,
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'OL112BA',
    newPnr: null,
    policy: 'Flexible coach · paid seats allowed',
    trip: 'New York → London · 19 Aug 2026',
    originBooking: 'BA 112 JFK–LHR 21:30',
    segments: [
      {
        from: 'JFK',
        fromCity: 'New York',
        to: 'LHR',
        toCity: 'London',
        flight: 'BA 112',
        airline: 'British Airways',
        depart: '21:30',
        arrive: '09:25',
        status: 'ok',
      },
    ],
    disruption: 'None',
    preferences: ['Aisle', 'Forward cabin'],
    loyalty: 'BA Silver',
    locationNow: 'Manhattan office',
    meetingConstraint: 'None',
    avaOutcome: 'Ava resolving — seat map presented, awaiting traveller confirm',
    avaPlan: [
      'Confirm seat 34D aisle at £46 (in policy)',
      'Ticket the seat in the original PNR',
      'Close chat without a consultant',
    ],
    resolvedByAva: false,
    genesysQueue: 'Genesys · Web chat · Skill: Servicing · demo data',
    nextBestActions: [
      {
        id: 'nba-o1',
        label: 'Let Ava finish the seat ticket',
        reason: 'Low complexity, high confidence self-serve.',
        owner: 'ava',
      },
    ],
    timeline: [{ id: 'to1', time: '07:11', actor: 'Ava', label: 'Seat map offered', detail: '34D aisle, £46' }],
    transcript: [
      { time: '07:10', from: 'Olivia', text: 'Can I get an aisle on tomorrow night’s BA flight?' },
      { time: '07:11', from: 'Ava', text: '34D is open for £46, within policy. Confirm and I’ll ticket it.' },
    ],
    options: [],
    messagePreview: {
      channel: 'chat',
      to: 'Olivia Stone',
      body: 'Seat 34D confirmed on BA 112. (demo)',
    },
  }
}

function arjunCase(): ServiceCase {
  return {
    id: 'case-arjun',
    interactionId: 'int-arjun',
    caseNumber: 'TX-1845',
    traveller: 'Arjun Mehta',
    company: 'Helios Capital',
    role: 'Analyst',
    phone: '+91 98 5550 0144',
    email: 'arjun.mehta@helios-capital.example',
    channel: 'email',
    intent: 'Invoice request',
    summary: 'Arjun needs a VAT invoice for last week’s BOM–LHR trip for finance close. Queued for servicing; no disruption.',
    urgency: 'low',
    confidence: 97,
    contextCompleteness: 88,
    workflow: 'servicing',
    inventoryFresh: true,
    stage: 'intake',
    selectedOptionId: null,
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'AJBOM44',
    newPnr: null,
    policy: 'Economy restricted',
    trip: 'Mumbai → London · 11–15 Aug 2026',
    originBooking: 'AI 131 BOM–LHR',
    segments: [
      {
        from: 'BOM',
        fromCity: 'Mumbai',
        to: 'LHR',
        toCity: 'London',
        flight: 'AI 131',
        airline: 'Air India',
        depart: '13:10',
        arrive: '18:25',
        status: 'ok',
      },
    ],
    disruption: 'None',
    preferences: [],
    loyalty: 'None',
    locationNow: 'Mumbai',
    meetingConstraint: 'Finance close 18:00 IST',
    avaOutcome: 'Queued — document generation pending',
    avaPlan: [
      'Generate VAT invoice from stored PNR AJBOM44',
      'Email traveller and finance@helios-capital.example',
      'No booking change',
    ],
    resolvedByAva: false,
    genesysQueue: 'Genesys · Email · Skill: Servicing-Billing · demo data',
    nextBestActions: [
      {
        id: 'nba-a1',
        label: 'Generate VAT invoice from stored PNR',
        reason: 'No booking change required.',
        owner: 'ava',
      },
    ],
    timeline: [{ id: 'ta1', time: '06:58', actor: 'Email', label: 'Invoice request received', detail: 'Subject: VAT invoice AI 131' }],
    transcript: [{ time: '06:58', from: 'Arjun', text: 'Please send the VAT invoice for AI 131 last week to finance@helios-capital.example.' }],
    options: [],
    messagePreview: {
      channel: 'email',
      to: 'Arjun Mehta · arjun.mehta@helios-capital.example',
      body: 'VAT invoice attached for AI 131 / PNR AJBOM44. (demo)',
    },
  }
}

function sofiaCase(): ServiceCase {
  return {
    id: 'case-sofia',
    interactionId: 'int-sofia',
    caseNumber: 'TX-1846',
    traveller: 'Sofia Rossi',
    company: 'Lumen Health',
    role: 'Medical advisor',
    phone: '+39 06 5550 0190',
    email: 'sofia.rossi@lumen-health.example',
    channel: 'phone',
    intent: 'Visa / document concern',
    summary:
      'Sofia holds an Italian passport and is travelling FCO–IAD tomorrow. She is unsure whether her ESTA is valid after a passport renewal. Ava cannot legally advise; routed to documentation specialist.',
    urgency: 'high',
    confidence: 62,
    contextCompleteness: 81,
    workflow: 'specialist',
    inventoryFresh: true,
    stage: 'intake',
    selectedOptionId: null,
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'SRFCO19',
    newPnr: null,
    policy: 'Flex Business',
    trip: 'Rome → Washington Dulles · 19–24 Aug 2026',
    originBooking: 'AZ 610 FCO–IAD 09:55',
    segments: [
      {
        from: 'FCO',
        fromCity: 'Rome',
        to: 'IAD',
        toCity: 'Washington',
        flight: 'AZ 610',
        airline: 'ITA Airways',
        depart: '09:55',
        arrive: '13:40',
        status: 'ok',
      },
    ],
    disruption: 'Document risk — possible ESTA mismatch',
    preferences: ['Keep original flight if document is valid'],
    loyalty: 'SkyTeam Elite Plus',
    locationNow: 'Rome · on phone',
    meetingConstraint: 'NIH briefing 20 Aug 09:00 ET',
    avaOutcome: 'Specialist review — Ava must not give immigration advice',
    avaPlan: [],
    resolvedByAva: false,
    genesysQueue: 'Genesys · Voice · Skill: Documents-Specialist · demo data',
    nextBestActions: [
      {
        id: 'nba-s1',
        label: 'Escalate to documentation specialist',
        reason: 'Immigration advice is out of consultant scope.',
        owner: 'specialist',
      },
    ],
    timeline: [{ id: 'ts1', time: '07:00', actor: 'Ava', label: 'Document intent classified', detail: 'Confidence 62% · specialist queue' }],
    transcript: [
      { time: '07:00', from: 'Sofia', text: 'I renewed my passport. Is my ESTA still valid for tomorrow?' },
      { time: '07:01', from: 'Ava', text: 'I can’t give immigration advice. I’m connecting you with a documentation specialist and keeping your booking on hold.' },
    ],
    options: [],
    messagePreview: {
      channel: 'phone',
      to: 'Sofia Rossi',
      body: 'A documentation specialist will call you back within 10 minutes. Your AZ 610 booking is unchanged. (demo)',
    },
  }
}

function lucaCase(): ServiceCase {
  return {
    id: 'case-luca',
    interactionId: 'int-luca',
    caseNumber: 'TX-1847',
    traveller: 'Luca Bianchi',
    company: 'Meridian Analytics',
    role: 'Sales director',
    phone: '+39 02 5550 2210',
    email: 'luca.bianchi@meridian-analytics.example',
    channel: 'email',
    intent: 'Carrier schedule change',
    summary:
      'Aer Lingus moved EI 520 MXP–DUB +40 minutes on the same ticket. No fare change, same PNR, in policy. Ava can accept the change and send the new itinerary without a consultant.',
    urgency: 'low',
    confidence: 94,
    contextCompleteness: 95,
    workflow: 'ava_contained',
    inventoryFresh: true,
    stage: 'intake',
    selectedOptionId: null,
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'LB520EI',
    newPnr: null,
    policy: 'Flex Business',
    trip: 'Milan → Dublin · 18 Aug 2026',
    originBooking: 'EI 520 MXP–DUB 07:25',
    segments: [
      {
        from: 'MXP',
        fromCity: 'Milan',
        to: 'DUB',
        toCity: 'Dublin',
        flight: 'EI 520',
        airline: 'Aer Lingus',
        depart: '08:05',
        arrive: '09:55',
        status: 'ok',
      },
    ],
    disruption: 'Schedule change +40 min · same ticket',
    preferences: ['Keep original PNR'],
    loyalty: 'AerClub Silver',
    locationNow: 'Milan office',
    meetingConstraint: 'Dublin stand-up 11:30 local — still makes it',
    avaOutcome: 'Ava resolving — awaiting accept of carrier schedule change',
    avaPlan: [
      'Accept +40 min on EI 520 (same fare family, same PNR)',
      'Keep original ticket — no reissue residual',
      'Email the updated itinerary',
    ],
    resolvedByAva: false,
    genesysQueue: 'Genesys · Email · Skill: Servicing-Schedule · demo data',
    nextBestActions: [
      {
        id: 'nba-l1',
        label: 'Let Ava accept the schedule change',
        reason: 'No policy exception, no meeting miss, no fare change.',
        owner: 'ava',
      },
    ],
    timeline: [
      { id: 'tl1', time: '06:44', actor: 'Aer Lingus', label: 'EI 520 retimed +40 min', detail: 'Same aircraft · demo data' },
      { id: 'tl2', time: '06:51', actor: 'Ava', label: 'Schedule-change offer drafted', detail: 'In policy · meeting still holds' },
    ],
    transcript: [
      { time: '06:51', from: 'Ava', text: 'Luca, Aer Lingus moved EI 520 to 08:05. Same seat, same fare. Your 11:30 Dublin stand-up still works. I can accept this for you.' },
      { time: '06:54', from: 'Luca', text: 'Yes, accept it. Don’t reissue unless you have to.' },
    ],
    options: [],
    messagePreview: {
      channel: 'email',
      to: 'Luca Bianchi · luca.bianchi@meridian-analytics.example',
      body: 'EI 520 now departs MXP 08:05, arrives DUB 09:55. Original PNR LB520EI unchanged. (demo)',
    },
  }
}

const jordanOptions = [
  {
    id: 'opt-aa177',
    recommended: true,
    airline: 'American Airlines',
    flight: 'AA 177',
    route: 'JFK → SFO',
    depart: '19:25',
    arrive: '22:52',
    duration: '6h 27m',
    cabin: 'Business',
    seats: 3,
    travellerCost: '$0',
    policyFit: 'Involuntary waiver on issued ticket · same fare family',
    confidence: 94,
    risks: ['Longer JFK dwell after BA 117 lands ~16:15.'],
    evidence: [
      {
        id: 'je1',
        label: 'Inventory',
        value: '3 J seats, last ping 12:16',
        source: demo('TravelXen inventory', '12:16', '2 min ago'),
      },
      {
        id: 'je2',
        label: 'Waiver',
        value: 'Airline involuntary waiver available',
        source: demo('GDS / BA-AA', '12:16', '2 min ago'),
      },
    ],
    notes: 'Ava can reissue on the already-issued ticket. No consultant GDS.',
  },
  {
    id: 'opt-aa19',
    airline: 'American Airlines',
    flight: 'AA 19',
    route: 'JFK → SFO',
    depart: '21:00',
    arrive: '00:28 +1',
    duration: '6h 28m',
    cabin: 'Business',
    seats: 5,
    travellerCost: '$0',
    policyFit: 'Waiver covers · later arrival',
    confidence: 90,
    risks: ['Lands after midnight PT. Board still holds tomorrow 09:00.'],
    evidence: [
      {
        id: 'je3',
        label: 'Inventory',
        value: '5 J seats, last ping 12:16',
        source: demo('TravelXen inventory', '12:16', '2 min ago'),
      },
    ],
    notes: 'Fallback if AA 177 drops at ticketing.',
  },
]

function jordanCase(): ServiceCase {
  return {
    id: 'case-jordan',
    interactionId: 'int-jordan',
    caseNumber: 'TX-1848',
    traveller: 'Jordan Hale',
    company: 'Summit Biologics',
    role: 'VP, Clinical Operations',
    phone: '+1 415 555 0198',
    email: 'jordan.hale@summit-biologics.example',
    channel: 'whatsapp',
    intent: 'BA 117 delay / missed AA 198',
    summary:
      'BA 117 LHR–JFK is delayed +2h 10m. AA 198 JFK–SFO will be missed. Ticket is already issued, rebooking eligibility is confirmed, an airline waiver is available, and supplier data is 2 minutes old. Ava can reissue without a consultant.',
    urgency: 'urgent',
    confidence: 95,
    contextCompleteness: 97,
    workflow: 'ava_contained',
    inventoryFresh: true,
    stage: 'brief_ready',
    selectedOptionId: 'opt-aa177',
    decision: null,
    decisionNote: '',
    escalateReason: '',
    overrideReason: '',
    verifiedBooking: false,
    verifiedMessage: false,
    pnr: 'JH117BA',
    newPnr: null,
    policy: 'Flex Business · involuntary disruption waiver',
    trip: 'London → San Francisco · 18–22 Aug 2026',
    originBooking: 'BA 117 LHR–JFK 11:05 / AA 198 JFK–SFO 16:55',
    segments: [
      {
        from: 'LHR',
        fromCity: 'London',
        to: 'JFK',
        toCity: 'New York',
        flight: 'BA 117',
        airline: 'British Airways',
        depart: '11:05',
        arrive: '16:15',
        status: 'delayed',
      },
      {
        from: 'JFK',
        fromCity: 'New York',
        to: 'SFO',
        toCity: 'San Francisco',
        flight: 'AA 198',
        airline: 'American Airlines',
        depart: '16:55',
        arrive: '20:40',
        status: 'missed',
      },
    ],
    disruption: 'BA 117 delayed +2h 10m · AA 198 connection will be missed',
    preferences: ['Same-day SFO', 'Protect issued ticket', 'No overnight JFK if a waiver seat exists'],
    loyalty: 'BA Gold · AAdvantage Gold',
    locationNow: 'London Heathrow T5 · airside · BA lounge',
    meetingConstraint: 'Board session, 09:00 PT tomorrow, South San Francisco',
    avaOutcome: 'Ava resolving — GDS facts allow autopilot reissue',
    avaPlan: [
      'Keep BA 117 (delayed) and drop missed AA 198',
      'Reissue AA 177 JFK–SFO 19:25–22:52 on the issued ticket',
      'File under airline waiver · $0 · message only after ticketing verifies',
    ],
    resolvedByAva: false,
    genesysQueue: 'Genesys · WhatsApp · Skill: Disruption-Rebook · Ava · demo data',
    nextBestActions: [
      {
        id: 'nba-j1',
        label: 'Let Ava reissue AA 177 on the issued ticket',
        reason: 'Eligibility confirmed, waiver available, supplier snapshot 2 min old. Consultant should not take this.',
        owner: 'ava',
      },
    ],
    timeline: [
      { id: 'tj1', time: '11:05', actor: 'Carrier', label: 'BA 117 delayed +2h 10m', detail: 'New JFK ETA 16:15 · demo data' },
      { id: 'tj2', time: '12:14', actor: 'GDS', label: 'AA 198 connection broken', detail: 'MCT at JFK will not hold' },
      { id: 'tj3', time: '12:16', actor: 'Ava', label: 'Read ticket, eligibility, waiver, freshness', detail: 'Issued · confirmed · available · 2 min ago' },
      { id: 'tj4', time: '12:17', actor: 'Ava', label: 'AA 177 held under waiver', detail: 'Same fare family · $0' },
    ],
    transcript: [
      { time: '12:14', from: 'Ava', text: 'Jordan, BA 117 is running +2h 10m. You will miss AA 198 at JFK. I’m checking your ticket and a waiver now.' },
      { time: '12:16', from: 'Jordan', text: 'Please get me to SFO tonight. Don’t make me rebuy.' },
      { time: '12:17', from: 'Ava', text: 'Ticket is issued, eligibility is confirmed, waiver is available. I’ll move you to AA 177, 19:25 JFK–SFO, no extra cost. I’ll confirm once it tickets.' },
    ],
    options: jordanOptions,
    messagePreview: {
      channel: 'whatsapp',
      to: 'Jordan Hale · +1 415 555 0198',
      body: 'Jordan — you’re on AA 177 JFK–SFO 19:25–22:52 in Business. BA 117 still flies (delayed). Original ticket protected, $0 under the airline waiver. Boarding pass follows when ticketing verifies. — Ava (demo)',
    },
    gdsFacts: [
      { id: 'ba117', label: 'BA117', value: 'Delayed +2h 10m', tone: 'alert' },
      { id: 'aa198', label: 'AA198', value: 'Connection will be missed', tone: 'alert' },
      { id: 'ticket', label: 'Ticket', value: 'Issued', tone: 'ok' },
      { id: 'elig', label: 'Rebooking eligibility', value: 'Confirmed', tone: 'ok' },
      { id: 'waiver', label: 'Airline waiver', value: 'Available', tone: 'ok' },
      { id: 'fresh', label: 'Supplier data freshness', value: 'Updated 2 min ago', tone: 'ok' },
    ],
  }
}

const interactions = (): Interaction[] => [
  {
    id: 'int-jordan',
    caseId: 'case-jordan',
    channel: 'whatsapp',
    time: '12:17',
    wait: '1 min',
    traveller: 'Jordan Hale',
    company: 'Summit Biologics',
    intent: 'BA 117 delay / missed AA 198',
    priority: 'urgent',
    state: 'ava_resolving',
    genesysId: 'GNS-WA-88490',
    ava: 'GDS: ticket issued · eligibility confirmed · waiver available · snapshot 2 min',
    routing: 'Disruption-Rebook · Ava',
    supervisor: {
      routeTo: 'ava',
      sentiment: 'anxious',
      vip: false,
      language: 'English',
      complexity: 'medium',
      confidence: 95,
      reason: 'Involuntary miss-connect on an issued ticket. Eligibility and waiver are confirmed and supplier data is 2 minutes old. Keep with Ava — do not open a consultant GDS session.',
    },
  },
  {
    id: 'int-maya',
    caseId: 'case-maya',
    channel: 'whatsapp',
    time: '11:52',
    wait: '6 min',
    traveller: 'Maya Patel',
    company: 'Meridian Analytics',
    intent: 'Missed connection / urgent rebooking',
    priority: 'urgent',
    state: 'ava_escalated',
    genesysId: 'GNS-WA-88421',
    ava: 'Escalated after self-serve offer; meeting constraint + fare protection',
    routing: 'Disruption-Rebook · consultant',
    supervisor: {
      routeTo: 'human',
      sentiment: 'stressed',
      vip: false,
      language: 'English',
      complexity: 'high',
      confidence: 93,
      reason: 'Ava offered self-serve. Maya asked for a person to protect business fare and a 19:30 ET meeting. Judgment required.',
    },
  },
  {
    id: 'int-daniel',
    caseId: 'case-daniel',
    channel: 'phone',
    time: '07:06',
    wait: '12 min',
    traveller: 'Daniel Kim',
    company: 'Northwind Robotics',
    intent: 'Flight cancelled',
    priority: 'high',
    state: 'waiting_triage',
    genesysId: 'GNS-VC-11092',
    ava: 'Inventory snapshot incomplete',
    routing: 'Disruption-Triage',
    supervisor: {
      routeTo: 'human',
      sentiment: 'stressed',
      vip: false,
      language: 'English',
      complexity: 'high',
      confidence: 71,
      reason: 'Cancellation on a live call, but inventory is 11 minutes stale. Do not autopilot. Hold until snapshot is fresh.',
    },
  },
  {
    id: 'int-olivia',
    caseId: 'case-olivia',
    channel: 'chat',
    time: '07:10',
    wait: '2 min',
    traveller: 'Olivia Stone',
    company: 'Brightline Media',
    intent: 'Seat selection',
    priority: 'low',
    state: 'ava_resolving',
    genesysId: 'GNS-CH-55201',
    ava: 'Seat map presented, awaiting confirm',
    routing: 'Servicing · Ava',
    supervisor: {
      routeTo: 'ava',
      sentiment: 'calm',
      vip: false,
      language: 'English',
      complexity: 'low',
      confidence: 89,
      reason: 'Seat-only, in-policy £46 aisle. No itinerary change. Keep with Ava — a consultant taking this steals a containment win.',
    },
  },
  {
    id: 'int-arjun',
    caseId: 'case-arjun',
    channel: 'email',
    time: '06:58',
    wait: '24 min',
    traveller: 'Arjun Mehta',
    company: 'Helios Capital',
    intent: 'Invoice request',
    priority: 'low',
    state: 'queued',
    genesysId: 'GNS-EM-33018',
    ava: 'Document generation pending',
    routing: 'Servicing-Billing',
    supervisor: {
      routeTo: 'ava',
      sentiment: 'neutral',
      vip: false,
      language: 'English',
      complexity: 'low',
      confidence: 97,
      reason: 'VAT invoice from a stored PNR. No booking change. Servicing AI can finish it.',
    },
  },
  {
    id: 'int-sofia',
    caseId: 'case-sofia',
    channel: 'phone',
    time: '07:00',
    wait: '8 min',
    traveller: 'Sofia Rossi',
    company: 'Lumen Health',
    intent: 'Visa / document concern',
    priority: 'high',
    state: 'specialist_review',
    genesysId: 'GNS-VC-11077',
    ava: 'Out of scope — specialist',
    routing: 'Documents-Specialist',
    supervisor: {
      routeTo: 'specialist',
      sentiment: 'anxious',
      vip: false,
      language: 'English',
      complexity: 'high',
      confidence: 62,
      reason: 'ESTA / passport question. Immigration advice is out of Ava and out of travel-consultant scope. Route to documents specialist.',
    },
  },
  {
    id: 'int-luca',
    caseId: 'case-luca',
    channel: 'email',
    time: '06:51',
    wait: '2 min',
    traveller: 'Luca Bianchi',
    company: 'Meridian Analytics',
    intent: 'Carrier schedule change',
    priority: 'low',
    state: 'ava_resolving',
    genesysId: 'GNS-EM-33044',
    ava: 'Accepting +40 min on same PNR',
    routing: 'Servicing-Schedule · Ava',
    supervisor: {
      routeTo: 'ava',
      sentiment: 'calm',
      vip: false,
      language: 'English',
      complexity: 'low',
      confidence: 94,
      reason: 'Carrier retimed the same flight. Meeting still holds. No fare change. Ava should accept — do not open a consultant ticket.',
    },
  },
]

const baselineSignals = (): LearningSignal[] => [
  {
    id: 'sig-1',
    time: 'Yesterday 16:40',
    caseNumber: 'TX-1790',
    traveller: 'Noah Berger',
    intent: 'Misconnect',
    outcome: 'Same-day partner reissue',
    consultantAction: 'Approved Ava option',
    whatWorked: 'Meeting-time constraint in the brief cut handle time by 4 min',
    playbookImpact: 'Keep calendar constraint in Case Brief v3',
    captured: true,
  },
  {
    id: 'sig-2',
    time: 'Yesterday 14:12',
    caseNumber: 'TX-1784',
    traveller: 'Priya Nair',
    intent: 'IRROPS overnight',
    outcome: 'Hotel + morning departure',
    consultantAction: 'Modified Ava hotel choice',
    whatWorked: 'Traveller rejected airport hotel; city hotel reduced complaint risk',
    playbookImpact: 'Prefer city hotel when dwell > 10h',
    captured: true,
  },
  {
    id: 'sig-3',
    time: 'Yesterday 11:05',
    caseNumber: 'TX-1771',
    traveller: 'James Okonkwo',
    intent: 'Seat paid',
    outcome: 'Ava contained',
    consultantAction: 'None — no handoff',
    whatWorked: 'Policy-priced seat map in chat',
    playbookImpact: 'Keep Ava containment for seat-only intents',
    captured: true,
  },
]

const baselineAvaRuns = (): DemoSnapshot['avaRuns'] => [
  {
    id: 'ava-1',
    time: '07:02',
    traveller: 'Priya Nair',
    caseNumber: 'TX-1839',
    intent: 'Paid seat',
    outcome: '14C confirmed · £38 in policy',
    status: 'resolved',
  },
  {
    id: 'ava-2',
    time: '07:08',
    traveller: 'James Okonkwo',
    caseNumber: 'TX-1840',
    intent: 'Name correction (minor)',
    outcome: 'Middle initial restored on stored PNR',
    status: 'resolved',
  },
  {
    id: 'ava-j',
    time: '12:17',
    traveller: 'Jordan Hale',
    caseNumber: 'TX-1848',
    caseId: 'case-jordan',
    intent: 'BA 117 delay / missed AA 198',
    outcome: 'Reading GDS · AA 177 held under waiver',
    status: 'running',
  },
  {
    id: 'ava-3',
    time: '07:11',
    traveller: 'Olivia Stone',
    caseNumber: 'TX-1844',
    caseId: 'case-olivia',
    intent: 'Seat selection',
    outcome: 'Awaiting 34D confirm · £46',
    status: 'running',
  },
  {
    id: 'ava-4',
    time: '06:51',
    traveller: 'Luca Bianchi',
    caseNumber: 'TX-1847',
    caseId: 'case-luca',
    intent: 'Carrier schedule change',
    outcome: 'Accepting +40 min · same PNR',
    status: 'running',
  },
]

export function createSnapshot(): DemoSnapshot {
  return {
    interactions: interactions(),
    cases: [jordanCase(), mayaCase(), danielCase(), oliviaCase(), arjunCase(), sofiaCase(), lucaCase()],
    signals: baselineSignals(),
    avaRuns: baselineAvaRuns(),
    selectedInteractionId: 'int-jordan',
    selectedCaseId: null,
    search: '',
    toasts: [],
    openCases: 18,
    urgentDisruptions: 5,
    avaResolvedToday: 52,
    contextCompleteness: 91,
  }
}

export const ESCALATE_REASONS = [
  'Policy exception above consultant authority',
  'Supplier inventory conflict at ticketing',
  'VIP / duty-of-care',
  'Documentation or immigration specialist required',
]

export const OVERRIDE_REASONS = [
  'Traveller declined the wait on the recommended flight',
  'Meeting time no longer holds on the recommended arrival',
  'Recommended inventory dropped at ticket issue',
  'Traveller requested a specific carrier',
]
